name: nvidia-4090-ci

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  pull_request:
    branches: [ '*' ]
    types: [opened, synchronize, reopened, closed]
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  test-4090-pytorch-2-7:
    name: Test 4090 (PyTorch 2.7)
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    uses: ./.github/workflows/reusable-ci-tests.yml
    with:
      runner: 'nvidia-4090'
      gpu_type: 'nvidia'
      conda_env_name: 'fla'
      pytorch_version: '2.7.0'
      skip_gpu_check: false
